import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ShoppingCartProvider } from "@/Context";
import MenuCheckoutProductsDetail from "@/components/MenuCheckoutProductsDetail";
import Footer from "../components/Footer/Footer";
import dynamic from "next/dynamic";

import Header from "@/components/Header";
import PreFooter from "@/components/PreFooter";
import { Toaster } from "react-hot-toast";

const FooterDynamic = dynamic(() => import("@/components/Footer/Footer"), {
  ssr: false,
});
const PrefooterDynamic = dynamic(() => import("@/components/PreFooter"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tiendi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ShoppingCartProvider>
      
    <html lang="en">
      <body className={inter.className}>
       
      <MenuCheckoutProductsDetail />
      <Header />
      <Toaster>
      </Toaster>
      {/* <Navbar /> */}
        {children}
        <PrefooterDynamic />
        <FooterDynamic />
        </body>
    </html>
    </ShoppingCartProvider>
  );
}
